### PR TITLE
Performance work

### PR DESCRIPTION
**Pull request by brainkim**
TODO:
- [ ] more tests to make sure we haven’t broken anything
- [x] stop using document.createDocumentFragment for single nodes wtf
- [x] stop using DocumentFragments entirely
- [x] tweaks to updateProps/updateChildren in DOM
- [x] make children responsible for removal from parents
- [x] more finely scoped usage of try/catch/finally
- [x] kill the Pledge abstraction for using too much memory 💀
- [x] optimize deletions so that children of parents which are already removed are removed (`HostContext.dirtyRemoval`)
- [x] don’t commit parents if the current node isn’t dirty
- [x] don’t update DOM attrs if we’re not updating (`HostContext.dirtyProps`)
- [x] use dynamic programming so host nodes don’t have to rerender children when they haven’t changed (`HostContext.dirtyChildren`)
- [x] CACHE INTRINSICS FUCKING DUH
- [x] get rid of HostContexts and just expose HostContexts to intrinsics directly
- [x] move committing logic outside of the updating logic
- [x] cloneNode not createElement
- [x] el.textContent for single nodes or clearing nodes
- [x] createElement optimizations
- [x] ~~stop initializing properties to undefined~~
- [x] don’t use symbols for keys
- [x] stop deleting crank-key from props.
- [x] [Optional] optimize deletion of nodes with (`HostContext.dirtyChildren`)
- [x] [Optional] optimize appending nodes (`HostContext.dirtyStart`)
- [x] [Optional] optimize prepending nodes (`HostContext.dirtyEnd`)
- [x] [Optional] make nodes singly linked
- [ ] [Optiona] group unmounting of children so it happens all at once
- [ ] [Optional] clear all nodes with `el.textContent = ""` if no shared children are found
- [ ] [Optional] clean up references on unmount and delete Contexts from the tree
- [ ] bikeshave on the names for the dirty flags
- [ ] [Optional] clean up onevent callbacks
- [ ] [Optional] some sort of automated benchmark directory which runs and measures performance.
- [ ] [Optional] 0.2.0 release where we don’t transpile our code
- [ ] [Optional] investigate more memory saving techniques (fewer anonymous functions maybe)
- [ ] [Optional] document renderer API and optimization flags
- [ ] submit PR to https://github.com/krausest/js-framework-benchmark
https://github.com/krausest/js-framework-benchmark/issues/441

### CODE REVIEW

**Comment by brainkim** [comment]
Fixed some of the low-hanging bottlenecks/issues. More work is definitely required. Specifically, Crank is using way too much memory. I suspect things like switching from a doubly-linked list to a singly linked list will help. Need to refactor and cleanup, but I’m sandboxing the current improvements so I can implement some features.

**Comment by ibsusu** [comment]
I don't know if this is added pressure, but I'm looking forward to the benchmarks.  I'm too much of a coward to use this yet.  God speed.

**Comment by brainkim** [comment]
@ibsusu
krabs_rag3do

**Comment by brainkim** [comment]
Alright, more work is gonna have to be done in a more scientific, methodical manner, but I found most of the basic bottlenecks for the js-frameworks-benchmark and I want to implement some features now so I’m sandboxing the work for now.

**Comment by brainkim** [comment]
God be with you if you’re trying to rebase against this I’m so sorry.

**Pull request merged**
