### PR TITLE
Schedule/Cleanup/refs

### PR DESCRIPTION
**Pull request by brainkim**
- [x] implement `Context.prototype.schedule`
- [x] implement `Context.prototype.cleanup`
- [x] basic tests
- [x] implement `crank-ref`
- [x] expose `value` and `props` on the context???
- [ ] more tests
- [ ] documentation ugh

Resolves: #33 #36 #82 probably other issues.

### CODE REVIEW

**Comment by ryhinchey** [comment]
Nice!  I like `cleanup` and `schedule`.

**Comment by brainkim** [comment]
YOLO

**Comment by virtualfunction** [comment]
Are there any docs on how to use these shiny toys?

**Comment by brainkim** [comment]
@virtualfunction Check out the updated docs. Specifically, the section on accessing rendered values (https://crank.js.org/guides/lifecycles#accessing-rendered-values) and the guide on reusable logic (https://crank.js.org/guides/reusable-logic). I’ll write more example code soon I just got tired of writing/editing docs.

**Comment by virtualfunction** [comment]
Oh, you've only just updated this in the last few days. How cheeky! (and thanks!)

**Pull request merged**
